### ISSUE TITLE
Error: No JWT_SECRET in env variable

### ISSUE THREAD

**Issue by themcguy** [amazingandyyy/mern-stack#9]
Hi, I get this error, but there are no instructions on how to fix it..

I have created an .env file and it's accessible, what do I put in it?

Thanks in advance!

**Comment by vantuanprimelabo** [comment]
Hey guy, I have issue same. Can you help me fix ?

**Comment by vantuanprimelabo** [comment]
mern-stack-server@1.0.2 build E:\GITHUB\mern-stack\server
> rm -rf ./dist && NPM_CONFIG_PRODUCTION=false babel -d ./dist ./src -s

'NPM_CONFIG_PRODUCTION' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mern-stack-server@1.0.2 build: `rm -rf ./dist && NPM_CONFIG_PRODUCTION=false babel -d ./dist ./src -s`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mern-stack-server@1.0.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by amazingandyyy** [comment]
@vantuanprimelabo  thx fot the feedback, it due to because you are not using linux-based machine, but it's okay, I fixed in the latest version server@1.0.3, please clone and do it again.

**Comment by amazingandyyy** [comment]
@themcguy please refer to the docs https://github.com/amazingandyyy/mern-stack#server-side-usageport-8000

**Comment by amazingandyyy** [comment]
pls feel free to reopen if the issue still exists

**Comment by Phlongs** [comment]
Looks like the issue still exists?  Im on windows
'NPM_CONFIG_PRODUCTION' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mern-server@0.0.1 build: `rm -rf ./dist && NPM_CONFIG_PRODUCTION=false babel -d ./dist ./src -s`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mern-server@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Home\AppData\roaming\npm-cache\_logs\2019-07-01T23_28_44_712Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mern-server@0.0.1 postinstall: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mern-server@0.0.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
